### ISSUE TITLE
URL query parameters are not preserved upon signup/login failure

### ISSUE THREAD

**Issue by sedubois** [heartcombo/devise#5113]
## Environment

- Ruby **2.6.3p62**
- Rails **5.2.3**
- Devise **4.6.2**

## Current behavior

My signup and login routes can accept extra URL query parameters, which are correctly forwarded to whatever route the user goes to after signing up or signing in, through a custom `after_sign_in_path_for` method in my `ApplicationController`.
<details>

```ruby
  # Example of redirecting based on a passed `path` URL query param 
  # after successful signup/sign in.
  # NB: other params, such as `coupon` (as part of a user subscription checkout flow) 
  # will probably be added as well.
  def after_sign_in_path_for(resource)
    if resource.is_a? Administrator
      rails_admin_path
    else
      path = (params[:user][:path] if params[:user]) || params[:path]
      if path.present? && URI.parse(path).relative?
        path
      else
        super
      end
    end
  end
```
</details>

However, if a validation error occurs when the user submits the sign in or sign up form, those URL query parameters get lost. E.g if the URL was `/users/sign_up?path=my-page-url` it will become `/users/sign_up` (with a flash message shown to the user describing what went wrong in their form submission, such as "this email is already taken", "incorrect password" or that sort of thing). This is because of the default `Devise::RegistrationsController#create` action which will execute `respond_with resource` when `resource.persisted?` is false.

## Expected behavior

It should be possible to preserve URL query parameters when the signup/login page is re-rendered because of a form validation error.

NB: What I store in the URL parameters is primarily the URL where I want the user to go after successful authentication. I am aware of the default `after_sign_in_path_for` implementation which does this through the session instead of URL parameters (`session['user_return_to']`), however according to my tests this was too fragile for us (if a user tries to visit an authenticated page and gets redirected to the login page, then fails to log in and abandons his login attempt, then comes back later and logs in again, he will still be brought back to the return_to URL even though by that time it isn't what he expects any more (as this might be hours or days later)).

NB2: even if for some reason we started to use the session instead of URL query params, there are still other parameters that would need to be passed through query params (e.g a coupon when signing up or logging in as part of a subscription checkout flow).

NB3: when looking into this it also made me realize that the `FailureApp`'s is apparently not used at all when there is a validation error with signup, only with login, which was quite confusing to me.

I could workaround this by defining custom registration and session controllers and overriding the `create` actions as follows:
```ruby
class Users::RegistrationsController < Devise::RegistrationsController

  # override create action in order to preserve URL query parameters
  # when there is a validation error (i.e. when resource.persisted? is false)
  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      # respond_with resource <-- original implementation from superclass
      redirect_to [:user, :registration, path: params[:user][:path], coupon: params[:user][:coupon]], alert: resource.errors.full_messages.join(', ')
    end
  end

end
```

Would there be a way to do this within Devise itself to avoid such workarounds?

Thanks for a great library!

**Comment by joshIsCoding** [comment]
An alternative solution that we have recently employed is to capture and store the query string parameter in a hidden field within the login form. So long as you ensure that you override/redefine the input name to match the key that the query string would have, you can seamlessly check for the presence of that key in the params within the after_sign_in_path_for method in the application controller. Overall, this involves less customisation than overriding the controller methods :) 

`f.hidden_field( :token, value: params[:token], name: 'token' ) if params[:token]`

Then, in the application controller (or wherever you may have overridden the devise method):

`def after_sign_in_path_for( resource )`
`    if params[:token]`
`     resource_path( token: params[:token] )`

**Comment by carlosantoniodasilva** [comment]
This is basically true for any GET/POST form in Rails: you go to a path, show a form, submit that form, and the submission doesn't necessarily carry over the params that were there when the form was displayed. You're responsible to use those params from the GET and pass them along to the POST, should you need it.

If you need additional params to be carried around, your best bet is what @joshIsCoding suggested: add hidden fields to your form, custom to your app, and/or pass those params around via the URL in the form, e.g. note the URL containing additional params:

```erb
<%= form_for(resource, as: resource_name, url: registration_path(resource_name, token: params[:token]), html: { method: :put }) do |f| %>
```

One alternative that's more generic is to provide `default_url_options` on your controller, which are params that are added to all URLs generated within actions on that controller, e.g.:

```ruby
  def default_url_options
    { foo: params[:foo] }
  end
```

These will be passed around via any URL generated there. You could define that on the controllers you want/need, or on the parent Devise controller for example.

[I _think_ this might not work for login by default because of how the failure app & warden works though](https://github.com/heartcombo/devise/blob/41e2db212065f2a75a5d73e76d6eb8ecd53a6acf/lib/devise/failure_app.rb#L26-L35), so for that you might still need to pass them around yourself. In any case, I don't think it's Devise's responsibility to handle params and pass them around, as it's impossible to know which params should be passed around and if that could expose things we should not.

> (if a user tries to visit an authenticated page and gets redirected to the login page, then fails to log in and abandons his login attempt, then comes back later and logs in again, he will still be brought back to the return_to URL even though by that time it isn't what he expects any more (as this might be hours or days later)).

I can see how that can be a problem, and I don't have a good solution to suggest for this yet... maybe in the future Devise could implement a timeout on this to drop that stored value from the session or something, so it's not there for a long time.

> NB3: when looking into this it also made me realize that the FailureApp's is apparently not used at all when there is a validation error with signup, only with login, which was quite confusing to me.

The failure app is used for authentication failures only. That includes trying to access an authenticated page while being unauthenticated, as well as trying to authenticate, but that's about it.
