### ISSUE TITLE
New Release request

### ISSUE THREAD

**Issue by getaaron** [heartcombo/devise#5183]
It's been a few months since there was a release, and I'd love to get a new one out so I don't need to get from `master` for the latest fixes.

**Comment by JalisoCSP** [comment]
It looks like there was a milestone (https://github.com/heartcombo/devise/milestone/11) for v5.0, last updated 7 months ago!

That sounds like a good point for a release :)

**Comment by seanfcarroll** [comment]
https://github.com/heartcombo/devise/releases/tag/v4.7.1

Can this be closed now @getaaron ?

**Comment by carlosantoniodasilva** [comment]
I released 4.7.2 back in June, I might cut a new one soon with a couple of fixes in master, but there's a deprecation I probably don't want included in there yet that I'll have to handle.

Anyway, that should be enough to close this one.

Also: I missed that milestone and 5-rc branch, I'll take a look at that, it was never pushed forward. (I have a plan to ship something along the lines of v5 as well)

Thanks all.

**Comment by gobijan** [comment]
Can we get the latest and greatest with 422 redirect for hotwire as 5.0 release?

**Comment by carlosantoniodasilva** [comment]
Those changes are not in master yet, I'm still investigating some other possible incompatibilities before releasing Responders and getting those changes ported / merged to Devise master. Also, there's plenty more to include in terms of possible breaking changes if we were to release a major 5.0 version of Devise, so that bump might take a while. Thanks.
