### ISSUE TITLE
Define the respond_to per resource

### ISSUE THREAD

**Issue by pupeno** [heartcombo/devise#5240]
When developing a mostly-API Rails application, I often find myself having two Devise resources, one for the admins accessing the admin tool and one for the users, accessed through the API. Something like this:

```ruby
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :admins

  scope "/api/v1", defaults: {format: :json} do
    devise_for :users
    # ...
  end
end
```

All the API controllers define `respond_to :json` so they don't answer to HTML but Devise still does because I couldn't find a way of modifying the `respond_to` configuration for one resource independently of the others.

I think having this feature, being able to define it on the routes or something like that would make making APIs easier and better.

**Comment by rafaelfranca** [comment]
Thank you for the request but currently there is no way to call `respond_to` dynamically and we have no interest on implementing that. What can be done if for you to create subclasses of the devise controllers for your resource and configure your app in the routes to use those new controller subclasses.

If you are interested on making this possible feel free to open a pull request.

I'm closing this issue since it is a feature request that we have no plan to implement.

Thank you.
