### ISSUE TITLE
For APIs return error codes on top of free form text

### ISSUE THREAD

**Issue by pupeno** [heartcombo/devise#5243]
When using Devise as an API for a frontend, I often want to have a control of error messages in the frontend, creating them there. I find myself writing code like this:

```javascript
switch (error.response.data.error) {
  case "You need to sign in or sign up before continuing.": // Blank form.
  case "Invalid Email or password.":
    setStatus(LogIn.INCORRECT_PASSWORD)
    break
  case "You have to confirm your email address before continuing.":
    setStatus(LogIn.EMAIL_CONFIRMATION_PENDING)
    break
  case "You have one more attempt before your account is locked.":
    setStatus(LogIn.ALMOST_LOCKED)
    break
  case "Your account is locked.":
    setStatus(LogIn.LOCKED_USER)
    break
  default:
    throw error
}
```

I think it would be good if Devise included an error code or short string that is more constant than an English sentence for the frontend to latch on. I think this should also happen in many if not all validation errors.

I know this probably feels a bit weird from the Rails side of things, but I think it would make Devise more friendly towards API consumers.

**Comment by rafaelfranca** [comment]
Thank you for the issue. We have no interest on this feature since we don't build API applications. If you think this should be supported I'm happy to review a pull request.

It is possible for you to define a new Responder and configure in the parent controller of Devise and override the `json_resource_errors` method to return something lik `errors.details`.

For more info see:

https://github.com/heartcombo/responders#configuring-your-own-responder
https://github.com/heartcombo/responders/blob/35dd3d90010610900b3fcca46ea96aac90144d19/lib/action_controller/responder.rb#L295

**Comment by theblang** [comment]
@rafaelfranca A struggle we're having is that, while it does make sense to leverage Devise's built-in translating, we want to do special logic in our SPA client for certain error cases. But as things are right now, you have to resort to checking text strings, which is pretty gross. Adding some kind of error code, perhaps something like the key used for translation, to the error response would provide something concrete to hinge off in a SPA client that's using Devise.
