### ISSUE TITLE
How to stub current_user in decorator method with rspec?

### ISSUE THREAD

**Issue by DIGITALSQUAD** [heartcombo/devise#5291]
I have a decorator(active_decorator) which refers current_user.

**event_decorator.rb**
```
module EventDecorator
  def applied?
    user_applied(current_user.id).exists?
  end
end
```

Included devise test controller but raises an error.
**rails_helper.rb**
```
config.include Devise::Test::ControllerHelpers, type: :decorator
```
**event_decorator_spec.rb**
```
describe 'applied?' do
  let(:event) { create(:event) }

  before do
    allow(event).to receive_message_chain(:user_applied, :exists?) { true }
  end

  it { expect( event.applied?).to be_truthy }
end
```
**Error message**
```
 NoMethodError:
       undefined method `env' for nil:NilClass
       Did you mean?  end
```
This message may come from 
https://github.com/heartcombo/devise/blob/eed641d2bea11839ab13e943660da41cad14314d/lib/devise/test/controller_helpers.rb#L43-L45

## Environment

- Ruby **[2.7.1]**
- Rails **[5.2.4.4]**
- Devise **[4.7.2]**

**Comment by carlosantoniodasilva** [comment]
`ControllerHelpers` are meant to be included in the context of a controller, they'll expect things to be there that only a controller can provide.

Since it's a module there, it looks like you can just stub `current_user` on `self` (or `event` in that case), and assume that's the contract you need/have.

```ruby
allow(event).to receive(:current_user) { my_user }
```

I don't really know how `event` would have a "current_user" though in your context (please provide a full example if you need further help), but it should be something along the lines above to get it working.

**Comment by DIGITALSQUAD** [comment]
Thanks for your comment but it doesn't work and raise the same error. (updated rspec code).
The`` event`` is a model that belongs to a  user,  but the current_user in event_decorator does not refer to the association but the current_user in session.  The EventDecorator method ``applied?`` is used only in views. 
```
class Event < ApplicationRecord
   belongs_to :user # applied? method does not refer to this association
end
```
When deleting including ``Devise::Test::Controller`` cause MissingWarden error (below).
```
Devise::MissingWarden:
       Devise could not find the `Warden::Proxy` instance on your request environment.
       Make sure that your application is loading Devise and Warden as expected and that the `Warden::Manager` middleware is present in your middleware stack.
       If you are seeing this on one of your tests, ensure that your tests are either executing the Rails middleware stack or that your tests are using the `Devise::Test::ControllerHelpers` module to inject the `request.env['warden']` object for you.
```

**Comment by carlosantoniodasilva** [comment]
Sorry I probably misunderstood your original comment/question. What does `decorate event` do? I'm assuming it's something like extending the given object with the decorator module?

I tried reproducing your scenario with a quick script, just not including Devise (because I think what you're hitting is not Devise specific), and this passes:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'rspec'
end

class User
  attr_reader :id

  def initialize(id:)
    @id = id
  end
end

class Event
  attr_reader :user

  def initialize(user:)
    @user = user
  end
end

module EventDecorator
  def applied?
    user_applied(current_user.id).exists?
  end
end

require "rspec/autorun"

RSpec.describe 'applied?' do
  let(:current_user) { User.new(id: 1) }
  let(:event) { Event.new(user: User.new(id: 2)) }

  before do
    decorate event
    allow(event).to receive_message_chain(:current_user, :id) { 1 }
    allow(event).to receive_message_chain(:user_applied, :exists?) { true }
  end

  def decorate(object)
    object.extend(EventDecorator)
  end

  it { expect(event).to be_applied }
end
```

Like I mentioned earlier, `Devise::Test::ControllerHelpers` are meant to be included in Controller specs only. If you're testing something in isolation that only needs a `current_user`, generally its best to just assume one is there by providing it.

**Comment by DIGITALSQUAD** [comment]
Sorry to bother you. I agree with you on the point that just provides ``current_user``. 
This is not a Devise issue but a decorator.
I've defined current_user in the test because the normal stubbing way doesn't work in this decorator. 
I know it's not a smart way but works somehow
Thanks for your help 🙏 
```
describe 'applied?' do
  let(:event) { create(:event, user: create(:user)) }

  before do
   module EventDecorator
      def current_user; end
    en
    decorate event
    allow(event).to receive_message_chain(:user_applied, :exists?) { true }
  end

  it { expect( event.applied?).to be_truthy }
end
```
