### ISSUE TITLE
Log users in instead of require confirmation email during account creation

### ISSUE THREAD

**Issue by Tectract** [heartcombo/devise#5313]
## Pre-check

I tried Stack Overflow, nothing.

## Environment

- Ruby (N/A)
- Rails 5.x
- Devise (latest stable)

## Current behavior

I set up my user model as "confirmable" so now when I create a user, it emails a confirmation email to the user which they must click before they are logged in. This is very bad for our site trying to onload users, as many people never make it past this hurdle for sign-ups!

## Expected behavior

I don't want confirmation emails before users can log in. I want to just log them in right away. I want confirmations to be optional, so they should have an option to click a button for a confirmation email later, whenever they want.

How can I update / override the confirmable module to make:

1) no confirmation necessary for login
2) no confirmation email sent during user creation
3) user can still create a valid confirmation email / token at a later time

Thanks!

**Comment by carlosantoniodasilva** [comment]
You can configure confirmable in your devise initialiser: https://github.com/heartcombo/devise/blob/45b831c4ea5a35914037bd27fe88b76d7b3683a4/lib/generators/templates/devise.rb#L137-L163.

I believe what you're looking for is `allow_unconfirmed_access_for`, which by default is set to `0.days` meaning confirmation is *required* before logging in. You can set that to any number of days or to `nil` if you want to allow access indefinitely while still having the optional confirmation email/behavior.

That doesn't prevent the email confirmation from being sent on user creation (your point 2), but given it's not *required* that might be fine for your use case. I hope that helps!

**Comment by Tectract** [comment]
thanks!

**Comment by Tectract** [comment]
Hi there, I see this 

    def skip_confirmation_notification!
      @skip_confirmation_notification = true
    end

here: https://github.com/plataformatec/devise/blob/master/lib/devise/models/confirmable.rb#L158

How can I set this to false in the devise config? I don't have any place in my source where "user.new" gets called, as I call that through the devise module...

I really need my server to NOT send initial confirmation emails, as this could confuse the users or be considered spam. Confirmation emails should only be sent upon demand by the user from their user page, in our application flow.

**Comment by carlosantoniodasilva** [comment]
If you really don't want confirmation emails to be sent on user creation, I think you can add a before create callback to your model that simply calls that skip method:

```ruby
before_create :skip_confirmation_notification!
```

This might be the simplest way to get it working that way you need it to.

Of course I don't know anything about the context of your app, but I wanted to mention that confirmation emails on signup are very common behavior and shouldn't confuse users or be considered spam, as long as they are the ones performing the user creation / signup action. If that's not the case (like if the accounts are being created automatically or on behalf of users) then I'd totally agree with the possible confusion. But like I said, just my 2 cents completely out of the context of your app. :)

Hopefully that works for you, let me know otherwise.
