### ISSUE TITLE
Log user out after the confirmation period ends

### ISSUE THREAD

**Issue by navneet-demodesk** [heartcombo/devise#5332]
Devise has a way of allowing users to login without confirming their email immediately by setting the allow_unconfirmed_access_for config var.

I have a setup for logging the user out of the application once the confirmation period ends. Also, I need the user to be only logged out at night at 2 AM. 

For this, I overrode the confirmation_period_valid method with the following - 

```ruby
def confirmation_period_valid?
  confirmation_time = confirmation_sent_at.in_time_zone(time_zone).end_of_day + 2.hours
  unconfirmed_access_time = self.class.allow_unconfirmed_access_for.ago.in_time_zone(time_zone)
  confirmation_sent_at && confirmation_time >= unconfirmed_access_time
end
```

But when I check after the expiration period, I am still able to use the application. The user is not logged out. 

Checking the rails console shows that the confirmation period is not valid for the user so that works.

**Comment by carlosantoniodasilva** [comment]
In general the user should not be able to access the authenticated actions anymore after the confirmation period passes, if they haven't confirmed yet. Once they hit the app again, that check should run and it'd not allow access anymore.

I believe the change in the check above doesn't fully follow the logic in devise, in that the "allow unconfirmed access" time isn't being honored because the confirmation sent time is being changed to "end of day + 2 hours", in order to try to achieve the "2 AM" requirement you seem to have. Maybe you need to change "unconfirmed access time" to apply the same rule?

In any case, I have just re-tested this with bare devise configuration setting the "allow unconfirmed access for" config to a couple of minutes, waiting, and I was successfully logged out, so it seems Devise is doing the right thing. If you're still having the issue and can confirm it's devise specific, please try providing a sample script or app showing the problem. Thanks.
