### ISSUE TITLE
UncaughtThrowError for public/uploads file not found scenario

### ISSUE THREAD

**Issue by vanboom** [heartcombo/devise#5362]
## Environment

- Ruby **2.5.0**
- Rails **5.2.4.5**
- Devise **4.7.3**
- Warden **1.2.9**

Under this scenario...

Rails 5.2.4.5 production with config.public_file_server = true
Attempt to access a file in public/uploads that does not exist, e.g. https://my.server.com/public/uploads/file_not_exist.png
This results in the UncaughtThrowError in Rack application...

Top two items from the backtrace...

...warden-1.2.9/lib/warden/proxy.rb:134 in authenticate!
...devise-4.7.3/lib/devise/controllers/helpers.rb:118 in `authenticate_client!`

The UncaughtThrowError happens for any invalid route, not just public/uploads/...

Prior to upgrading my app to Rails 5.2.4.5, on Rails 4.1.8 / Devise 4.7.1 / Warden 1.2.7, the request would throw an ActionController::RoutingError

I am still investigating - any tips much appreciated.

**Comment by carlosantoniodasilva** [comment]
Can you show the entire trace and/or logs? It seems like somewhere is triggering the authentication even though it's a public file that should be handled by `ActionDispatch::Static`, which is why Devise is shown there.

Maybe something in your Rails middleware changed the order too, you can check it with `rake middleware`.

This seems very unlikely to be a Devise specific issue, but any other information could help troubleshoot.

**Comment by vanboom** [comment]
Thanks for the middleware tip - I am using [apartment](influitive/apartment) gem and  middleware in the wrong place.  The middleware stack changed when I moved to Rails 5.2.4.5 - your tip helped me correct the issue.  Thanks!
