### ISSUE TITLE
Devise::RegistrationsController#create wrong number of arguments (given 3, expected 1..2) on adding errors

### ISSUE THREAD

**Issue by notwedtm** [heartcombo/devise#5370]
## Environment

- Ruby **3.0.0-p0**
- Rails **6.1**
- Devise **HEAD**

## Current behavior

https://github.com/notwedtm/rails-6.1-devise-mongoid using this repo. Attempt to create two users with the same email address. When devise attempts to add the error, the argument count error is thrown.

It should be noted that with Ruby 2.7.2 this does not occur.

## Expected behavior

No error should be thrown.

**Comment by carlosantoniodasilva** [comment]
I don't have mongo installed right now on this computer but I'll try setting it up and running the app, thanks for that.

Are you able to show the full stack trace? And does it happen with Active Record instead of Mongoid?

**Comment by carlosantoniodasilva** [comment]
I found people reporting issues with Rails 6.1 + Ruby 3 in the mongoid repo here: https://github.com/mongodb/mongoid/pull/4944, seems to be related to I18n kwargs on validations that mongoid implements similar to AR, in that case I'll close this one as a mongoid issue instead of Devise. Maybe you can comment in the repo there and show your app as an example (perhaps even a sample app without devise which should also show it). Thanks for reporting.
