### ISSUE TITLE
NameError: uninitialized constant ApplicationRecord

### ISSUE THREAD

**Issue by talshr** [heartcombo/devise#5379]
## Pre-check

- Do not use the issues tracker for help or support, try Stack Overflow.
- For bugs, do a quick search and make sure the bug has not yet been reported
- If you found a security bug, do not report it through GitHub. Please send an e-mail to heartcombo@googlegroups.com instead.
- Finally, be nice and have fun!

## Environment

- Ruby **2.5.8p224**
- Rails **6.1.3**
- Devise **4.8.0**

## Current behavior

I've installed devise and generated the migration.
However I'm encountering this error when trying to migrate:

NameError: uninitialized constant ApplicationRecord
/root/myapp/app/models/user.rb:1:in `<top (required)>'

Not sure why, because ApplicationRecord should be supported in rails 6.

**Comment by seuros** [comment]
do you have a file app/models/application_record.rb ?

PS : `coding as root is very dangerous.`

**Comment by carlosantoniodasilva** [comment]
Also: does it work without Devise, and fails only with it?

The error doesn't seem to mention or point to anything related to Devise apparently, so I'm inclined to think it's unrelated to the library. If you are able to reproduce just with Devise and can send some script or app reproducing the problem, I'll be happy to take a better look. Thanks.

**Comment by talshr** [comment]
@seuros I don't have that file..
@carlosantoniodasilva  the user.rb file was generated after creating the devise migration (`rails g devise User`) so it's related...

**Comment by carlosantoniodasilva** [comment]
@talshr devise triggers the Rails / Active Record generator to create the model if it doesn't exist:
https://github.com/heartcombo/devise/blob/c82e4cf47b02002b2fd7ca31d441cf1043fc634c/lib/generators/active_record/devise_generator.rb#L25

And that should create a model inheriting from `ApplicationRecord` (instead of the "old" way from `ActiveRecord::Base`): https://github.com/rails/rails/blob/255b5ff9af57f9b54dee7ec884b12a1ad16f0321/activerecord/lib/rails/generators/active_record/model/model_generator.rb#L57

If you don't have `ApplicationRecord` in your app its probably because it's been upgraded over time and never created one, so other models are likely inheriting from `ActiveRecord::Base`... You can either just change the user model to inherit from it too, or create an `ApplicationRecord` as that's expected to exist going forward. You can do that via the `active_record:application_record` generator. Hope that helps.

**Comment by talshr** [comment]
Yes already solved this way thank you!

**Comment by MR-RenatoBlue** [comment]
Thanks. This helped me too. I had the same error because I've added "devise_for :users" in config/routes.rb before running 
$ rails generate devise User
