### ISSUE TITLE
"authenticate_user!" is it authorization or authentication?

### ISSUE THREAD

**Issue by couchbelag** [heartcombo/devise#5389]
## Environment

- Ruby **2.6.7**
- Rails **6.0.3.6**
- Devise **4.7.3**

## Current behavior

Well, this is not really a bug but a question regarding documentation. Reason why I'm not asking this in stackoverflow is, that maybe there are more people out there reading devise's documentation and wondering about the same question. But first I'll try to give you an overview of our setup. We've been integrating rails with doorkeeper as oauth provider, devise for authentication and cancancan for authorisation. We've been experiencing some difficutlies getting doorkeeper, devise and cancancan to play nicely, but solved it finally. However, we're not sure if we applied devise in a correct way. In documentation and examples I found, there is always `authenticate_user!` as before_action on top of a controller (or even in ApplicationController). But for doorkeeper to work we had to remove it... and as far as I understand `authenticate_user!` acts quite similar to `current_user` from authentication point of view (except for raising an exception). I would assume that it's ok to remove `authenticate_user!` and let cancancan alone do authorisation for controllers, but some of my team members have a bad feeling about this. So question is, is `authenticate_user!` a requirement to have a secure integration of devise or just a recommendation or best practice on how to authorize users to controllers? In the latter case I think `authenticate_user!` is the wrong name for that method and it should be named `authorise_user!`. I know backwards compatibility and stuff, but maybe just an alias would help many people (if my assumptions are correct of course). 

## Expected behavior

Clarification in documentation (Getting started) about how and when to use `authenticate_user!`. Maybe implementation of an alias with name `authorise_user!`.

**Comment by carlosantoniodasilva** [comment]
Devise is all about authentication, very little to nothing about authorization.

Authentication ensures you have an identified user/person (or whatever you call it), authorization guarantees they have the right privileges to access information or perform actions. Sometimes the line is blur because simply having an authenticated user also means that's all the authorization they need to perform whatever they need in the system, but more often than not you need additional checks to determine whether the currently authenticated person can really access/perform things.

And you can also use some level of authorization with Devise by separating authenticated models, to some extent (e.g. User and Admin). But in reality, more detailed authorization is something that cancan and pundit for example can provide, not devise.

In order to ensure you always have a logged in user (or whatever you choose to call it), you need to call the `authenticate_user!` or a similar `current_user`. I believe that not needing to call this in your case is due to doorkeeper integration, they have some recommendations in their wiki: https://github.com/doorkeeper-gem/doorkeeper/wiki/Running-Doorkeeper-with-Devise, and it seems they explain not needing to call `authenticate_user!` (or similar) because that's handled by doorkeeper's `resource_owner_authenticator` logic. (which you might have in one of your initializers, I presume.) 

That should replace the need to call `authenticate_user!` where you use doorkeeper.

**Comment by couchbelag** [comment]
Thanks for the confirmation! That `resource_owner_authenticator` is the key, yes, forgot about that one.
