### ISSUE TITLE
rememberable module using deprecated method

### ISSUE THREAD

**Issue by kossy0701** [heartcombo/devise#5421]
## Summary
Thanks you make amazing Gem. and all contributers.

I think need to modify the "changed?" method in rememberable module. Because it is deprecated.

This method has been deprecated in rails 5.1 and above. so need to use "has_changes_to_save?" instead of "changed?".

## Fix Proposal

https://github.com/heartcombo/devise/blob/main/lib/devise/models/rememberable.rb#L53

```
def remember_me!
  self.remember_token ||= self.class.remember_token if respond_to?(:remember_token)
  self.remember_created_at ||= Time.now.utc
  
  if Devise.activerecord51?
    save(validate: false) if self.has_changes_to_save?
  else
    save(validate: false) if self.changed?
  end
end
```

**Comment by carlosantoniodasilva** [comment]
The `changed?` method is not deprecated, iirc what was deprecated was the behavior in after_* callbacks since it was confusing. `changed?` has the same meaning of `has_changes_to_save?`, but the latter only exists in Active Record and clarifies (is less confusing) the behavior that it is only "true" before the save actually happens. (i.e. in before_* callbacks), but both are interchangeable.

If you have a reference of that deprecation, please let me know and I can take another look. Thanks.
