### ISSUE TITLE
current_user - load associations

### ISSUE THREAD

**Issue by alec-c4** [heartcombo/devise#5452]
Hey!
I have the following model

```ruby
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
    :confirmable, :lockable, :timeoutable, :trackable,
    :recoverable, :rememberable, :trackable, :validatable

  has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_fit: [150, 150]
    attachable.variant :medium, resize_to_fit: [300, 300]
    attachable.variant :large, resize_to_fit: [500, 500]
  end
end
```

and I've enabled strict loading mode to avoid the N+1 problem as [described here](https://www.bigbinary.com/blog/rails-6-1-adds-strict_loading-to-warn-lazy-loading-associations). I can preload associations when I work with other user instances as in users_controller

```ruby
  def set_user
    @user = User.includes([:login_activities, :roles], avatar_attachment: :blob).find(params[:id])
  end
```
 But I cannot preload associations for current_user, in my case - I'd like to preload ActiveStorage attachment's blobs, but I can't. Any ideas/suggestions on how to do it?

**Comment by PedroAugustoRamalhoDuarte** [comment]
Hello @alec-c4 , i reckon the best way to do this is override current_user method like that:
```ruby
# application_controller.rb
def current_user
  @current_user ||= super.tap do |user|
    ::ActiveRecord::Associations::Preloader.new.preload(user, avatar_attachment: :blob)
  end
end
```
Use this only if you use this avatar in all places on your app, otherwise is better to build a new query to get the avatar or create an method like current_user_with_avatar with the same body above.

**Comment by carlosantoniodasilva** [comment]
@alec-c4 I think you could simply load them upfront in a before action like this:

```ruby
current_user.login_activities.load
current_user.roles.load
# and so on.
```

Since there's always a single user, I'm not sure these are really considered N+1 as it's essentially going to do a single query for each via preload or manual loading like that.

The actual "find" calls happen [within ORM Adapter](https://github.com/ianwhite/orm_adapter/blob/master/lib/orm_adapter/adapters/active_record.rb) so it can get somewhat tricky to preload them with the find.

The solution suggested by @PedroAugustoRamalhoDuarte should work too I think. (although I'm not sure how much that preloader API is really public.)

**Comment by coorasse** [comment]
The new version of the code posted by @PedroAugustoRamalhoDuarte 

```
def current_user
    @current_user ||= super.tap do |user|
      ActiveRecord::Associations::Preloader.new(records: [user], associations: [:login_activities, :roles, avatar_attachment: :blob]).call
    end
  end
```
