### ISSUE TITLE
Rails 7 + Devise + Tailwindcss

### ISSUE THREAD

**Issue by evertonlopesc** [heartcombo/devise#5464]
## Pre-check

- Creating a new project without errors and with the stack below. 

## Environment

- Ruby 3.1.0
- Rails 7.0.1
- Devise both {
  - gem 'devise', github: 'heartcombo/devise', branch: 'main'
  - gem 'devise'
}
- Tailwindcss 2

## Current behavior

- No error

## Expected behavior
- Happy

## My Solution
- Install rails without tailwindcss (e.g. rails new app_name -d=database)
- Install devise gem 

> $ rails generate devise:install

- Devise install:

> $ rails generate devise:install

-  Added in config/initializers/devise.rb:

> config.navigational_formats = ['*/*', :html, :turbo_stream]

- User model create

> $ rails generate devise "MODEL"

- Add authentication and routes configuration etc.
- Generate devise views and not user views

> $ rails generate devise:views

- Added tailwindcss

> [Install Tailwind CSS with Ruby on Rails](https://tailwindcss.com/docs/guides/ruby-on-rails)

**Comment by rubydesign** [comment]
Got here by googling the topic, but i am not understanding the issue.

I have a rails 7 app and installed tailwind 3 , and then devise. No problem, all green.

I was looking for a tailwind styling, and found and excellent solution here https://github.com/posiczko/devise-tailwindcssed

Since a good solution (to the tailwind styling) exists, and this can not really be considered devise's responsibility, i think this issue should be considered closed
