### ISSUE TITLE
Do generated views and locales have to be renamed?

### ISSUE THREAD

**Issue by mices** [heartcombo/devise#5532]
I'm really confused about this Can I use them as is or do I have to rename them? Also I ran rails g devise:views and couldn't find "Invalid Email or password." in the newly generated devise.en.yml file Why is that?

**Comment by carlosantoniodasilva** [comment]
@mices you can keep them where they are generated, i.e. under `app/views/devise`, or move them to specific places if you override the controllers... for example if you create your own `SessionsController < Devise::SessionsController`, you can technically put the sessions views under `app/views/sessions` instead of `app/views/devise/sessions`. Both should work with the Rails template lookup.

As for the `devise.en.yml`, that contains all text translations for validations errors and flash messages. Views themselves aren't using that translation, you can update the views directly yourself, or use some 3rd-party like https://github.com/tigrish/devise-i18n that does use locale files.

The "Invalid Email or password" in particular is this one: https://github.com/heartcombo/devise/blob/7f419bf99adb9463617be7ccb0852d5f8f7b0317/config/locales/en.yml#L12, but `Email` is dynamic there... (email is your "authentication key", but that could be a username field, or something else entirely, so we interpolate that dynamically.... but nothing stops you from changing that to anything else)

Hope that helps!
