### ISSUE TITLE
Filter chain halted as :verify_signed_out_user rendered or redirected

### ISSUE THREAD

**Issue by godfreymutebi** [heartcombo/devise#5607]
- Hey guys, I have added activeadmin to a ruby on rails api with devise already implemented with jwt. 
- When i click on the logout i get this error in the console `Filter chain halted as :verify_signed_out_user rendered or redirected
`

- I expect activeadmin users to be redirected to the login page after logout , but the redirect is not working

- what could be the cause

**Comment by carlosantoniodasilva** [comment]
Does it only happen with active admin? That's triggered when it reaches Devise's sign out code without any signed in user, so it could be a problem with active admin's implementation or your integration.

Without a way to reproduce it, there's not much we can do. If you'd like to try recreating in a sample app we can take another look, otherwise I'd recommend checking with active admin's issues.
