### ISSUE TITLE
Redirects doesn't keep port number locahost

### ISSUE THREAD

**Issue by GuiGreg** [heartcombo/devise#5618]
All redirect from Devise loses the port number on localhost.
For example, will redirect to `localhost/users/sign_in` instead of `localhost:8020/users/sign_in`

I am running the rails app inside Docker.

**Comment by carlosantoniodasilva** [comment]
Devise and Responders do nothing special with redirects, they simply trigger it with the given paths, Rails should be prepending / handling the rest.

That said, it could be something with your setup that's losing the port, are you able to make other redirects work, just not within Devise? Try to debug requests and see what the request domain/host/port/fullpath is, it could give you some hints.

I don't think this is a Devise issue, but if you can provide a sample application that shows otherwise, we can take a better look.
