### ISSUE TITLE
ActionController::InvalidAuthenticityToken in Devise::SessionsController#create

### ISSUE THREAD

**Issue by venkat071982** [heartcombo/devise#5652]
Ruby 3.2.2
Rails 7.0.8
Devise 4.9.2

## Current behavior

Extremely frustrating. All of a sudden I try to login/register I get Can't verify CSRF token authenticity..

I didn't do any changes and it was all working fine 1h ago.

Stack trace:

....
        def handle_unverified_request
          raise ActionController::InvalidAuthenticityToken, warning_message
        end
      end
    end
...
PS: Yes I have the CSRF and CSP tags:

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

**Comment by venkat071982** [comment]
![Screenshot from 2023-11-06 19-57-53](https://github.com/heartcombo/devise/assets/32546941/29055a87-cdad-4fbf-892c-abfb06324b2d)

**Comment by adnanpirota** [comment]
I'm stuck on this too, but only in production

**Comment by DonatienD** [comment]
Encoutering the exact same on my local server, with ActiveAdmin.

**Comment by DonatienD** [comment]
We fixed it on our end by removing the following from `config/application.rb`:
```ruby
config.action_dispatch.cookies_same_site_protection = :none
config.action_controller.default_protect_from_forgery = false if ENV['RAILS_ENV'] == 'development'
```

**Comment by wenlingang** [comment]
I had the same problem when upgrading from rails 7.0 to 7.1

**Comment by leoplct** [comment]
Same issue after upgrading to Rails 7.1.2

It works on development, but not on staging/production

config.session_store :cookie_store, key: "_session", expire_after: 1.year

**Comment by alexdesi** [comment]
> I had the same problem when upgrading from rails 7.0 to 7.1

Same for me, can I ask you how did you fix?

**Comment by leoplct** [comment]
> > I had the same problem when upgrading from rails 7.0 to 7.1
> 
> Same for me, can I ask you how did you fix?

Upgrade to ruby 3.2, then be sure to have 

**config/enviroment/production.rb**

`config.session_store :cookie_store, key: "_example_session", expire_after: 1.year, domain: ".example.com"`

app/controller/application_controller.rb

**Comment by wenlingang** [comment]
> > I had the same problem when upgrading from rails 7.0 to 7.1
> 
> Same for me, can I ask you how did you fix?

I found that changing the session and so on didn't work, and then upgrading to rails 7.1.2 solved it

**Comment by grin** [comment]
I was running into the same issue with Rails 7.1.2 and Devise 4.9.3, what fixed it in my case (based on this comment: https://github.com/heartcombo/devise/issues/5298#issuecomment-1775911730)
was the puma upgrade to 6.4.2 from 5.6.4.

**Comment by GuillaumeGillet** [comment]
Same problem with rails 6.1

**Comment by serg-kovalev** [comment]
In my case I fixed it in `config/initializers/session_store.rb`:
by adding `domain: :all` and changing `cookie_store key` to handle various environments like `_#{Rails.env}`.
Something like that:
```ruby
Rails.application.config.session_store :cookie_store, key: "_my_name_#{Rails.env}", expire_after: 1.year, domain: :all
```

Also I'm using nginx in development, so, for my proxy I've ensured that the host header is correct to handle same origin verification problem (if you have a frontend on a separate localhost:port) and combining them together on the same host by using nginx:

```nginx
location / {
      proxy_set_header HOST $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_pass_request_headers on;
      proxy_pass   http://rails_backend;
      proxy_buffers 8 1024k;  
      proxy_buffer_size 1024k;
  }
```
I had issues when I used `$host`, but not `$http_host`

Might be useful for someone like myself who struggled with the issue for a few hours

**Comment by jean-francois-labbe** [comment]
Faced similar issue, here is the story. Maybe it could help someone.

When removing  `domain: :all, tld_length: 2` from the `session_store` configuration.
Going from:
```ruby
# kept only meaningful elements of the configuration
Rails.application.config.session_store :redis_store,
  key: "_session_identifier", expire_after: 14.days, domain: :all, tld_length: 2, secure: true
``` 
To
```ruby
Rails.application.config.session_store :redis_store,
  key: "_session_identifier", expire_after: 14.days, secure: true
```
The issue was visible immediately after deployment, no need to way for stale cookies...
 
**Context**
Devise is configured to use the `:rememberable` feature (`remember_user_token` cookie)
We moved an application from the domain (example.com) to multiple subdomains (eu.example.com and now us.example.com) with different application servers. During the migration we wanted users to stay logged in, that's why `domain: :all, tld_length: 2` to the `session_store` configuration, so that cookies on `example.com` could be reused on `eu.example.com` domain.

Before the change the server would set a `_session_identifier` cookie on the `.example.com` domain.
After removing `domain: :all, tld_length: 2`. This resulted in the server generating a new  `_session_identifier` cookie with the same name as the previous one but set on `eu.example.com`.

As the user was identified by the `remember_user_token`, users would still be logged in. But when submitting a form they would face the `ActionController::InvalidAuthenticityToken`.

**Why ?**
After deployment. When getting a page the server generates a `csrf_token` which is stored in the session and inserted in the html page (meta tag and hidden form field). the session uses the new configuration no `domain: :all, tld_length: 2`. which results in a new `_session_identifier` cookie sent to the browser. 

When submitting the form the browser would send the two `_session_identifier` cookies, one generated when the configuration was `domain: :all, tld_length: 2` and one new generated with `domain: :all, tld_length: 2`.
According to the HTTP RFC:
> * Among cookies that have equal-length path fields, cookies with earlier creation-times are listed before cookies with later creation-times.
This results in the browser sending the oldest  `_session_identifier` cookie first (the one created with `domain: :all, tld_length: 2`) and the latest  `_session_identifier` cookie last. cookies have different values (session identifier).

The server will use the oldest `_session_identifier` cookie to retreive a session from the session store. The old session would not contain the same `csrf_token` as the one submitted by the browser.

**How did I fix it ?**

1) Changed the session cookie name
```ruby
#   Users would still be logged in thanks to the `remember_user_token`

Rails.application.config.session_store :redis_store,
  key: "_new_session_identifier", expire_after: 14.days, secure: true
```

2) Cleanup previous cookies
```ruby
class ApplicationController < ActionController::Base
  before_action do
    if request_format == :html
      cookies.delete(: _session_identifier, domain: :all)
      cookies.delete(:remember_user_token, domain: :all)
      current_user.remember_me! if current_user
    end
  end
end
```

**Comment by iprog21** [comment]
> We fixed it on our end by removing the following from `config/application.rb`:
> 
> ```ruby
> config.action_dispatch.cookies_same_site_protection = :none
> config.action_controller.default_protect_from_forgery = false if ENV['RAILS_ENV'] == 'development'
> ```

is this safe?

**Comment by martijnenco** [comment]
> > We fixed it on our end by removing the following from `config/application.rb`:
> > ```ruby
> > config.action_dispatch.cookies_same_site_protection = :none
> > config.action_controller.default_protect_from_forgery = false if ENV['RAILS_ENV'] == 'development'
> > ```
> 
> is this safe?

You literally have configured now: `same_site_protection = :none` and `protect_from_forgery = false`. I think it's a safe bet that isn't the save option..

**Comment by martinbarilik** [comment]
session_store.rb before fixing the error:

`AppName::Application.config.session_store :cookie_store, key: "_eu_session",domain: :all`

session_store.rb after fixing the error:

`AppName::Application.config.session_store :cookie_store, key: "_eu_session_#{Rails.env}",
	expire_after: 14.days, domain: :all, secure: true`

I was getting all kinds of errors mentioned above including CRSF token and unauthorized access only in production env. I was getting extra `["` in cookie name as `["_cookie_name`. With change above the name is now `_cookie_name`.

Now i can log in again. 🎆🎆🎆

**Comment by martinbarilik** [comment]
> gem 'rack', '~> 2.2'

this is what caused problem in prod for me, switching to 2.2 fixed it temporaly, i am on an old machine and upgrading passenger to a 6.0.20+ version is no go for now ( which may support rack 3 already )

**Comment by nashby** [comment]
Closing this as it seems it's fixed. Feel free to ping me if you think Devise can handle it better somehow.
